import libs
from socket import *
from SenderController import *

sc = SenderController("localhost", 80)
sc.sendMessage("""Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris id lectus porta, tincidunt velit in, sollicitudin tortor. Phasellus lorem sem, efficitur ac efficitur quis, facilisis fringilla massa. Nunc a turpis ligula. Sed accumsan, purus a lacinia fringilla, neque dui dapibus metus, ac suscipit lacus lacus vitae ante. Nullam fermentum mauris eu augue consequat commodo. Fusce gravida volutpat felis. Ut tortor tortor, bibendum at dictum eu, vestibulum eget metus. Sed leo ipsum, elementum sed est ac, consequat cursus lectus. Vivamus eget magna nisi. Nam porttitor arcu diam, hendrerit egestas arcu aliquet et. Etiam interdum condimentum lacus, aliquet euismod enim vulputate at. Nunc porttitor lobortis felis nec ultricies. Donec suscipit, magna id interdum lobortis, metus elit molestie ligula, in facilisis sem nunc in felis.

Suspendisse varius felis nec volutpat ultrices. Phasellus dignissim vestibulum metus, eu porta tortor congue in. Proin facilisis rutrum dui, vel semper libero. Fusce diam ipsum, faucibus at nisi ac, pulvinar sollicitudin diam. Pellentesque mattis tortor orci, id vulputate justo auctor nec. Nunc vitae commodo odio. Nullam pulvinar purus eget ante consectetur, at tincidunt dui cursus. In eu elementum erat. Cras porta nibh sit amet feugiat ullamcorper. Donec pretium sem at sapien eleifend molestie in eu eros.

Vestibulum id enim ac lectus cursus ultrices. Nullam lacinia, ligula vel ullamcorper venenatis, justo metus vestibulum enim, ut volutpat nibh lorem et urna. Phasellus condimentum risus eget nisl ornare, id sollicitudin nulla sagittis. Donec ut diam semper, scelerisque nisi ut, volutpat erat. Pellentesque sem ipsum, bibendum et auctor vitae, mattis eget tortor. Sed sed nunc ante. Mauris semper ante quis lacus ultrices semper. Maecenas nunc quam, porta in orci non, semper vehicula nunc. Mauris dui orci, dapibus sit amet nisl at, malesuada ullamcorper nulla. Nullam quis urna nibh. Praesent sit amet purus est. Etiam quis tempor urna, ut laoreet nibh. Nam vitae viverra tortor.

In fringilla risus nec nulla dignissim efficitur. Integer a varius ex. Suspendisse potenti. Maecenas ac rhoncus nibh, ut luctus sapien. Ut consectetur sapien non consectetur euismod. Aenean pellentesque diam bibendum leo pulvinar blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sit amet nunc risus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque consectetur risus eros, sit amet consectetur quam porta vitae. Sed tempus iaculis metus. Suspendisse ante diam, porta eget nulla fermentum, efficitur blandit arcu. Curabitur lorem neque, elementum vel nunc in, pulvinar molestie nisi. Sed non augue in dolor blandit scelerisque.

Aliquam dui libero, molestie ut iaculis in, commodo rutrum turpis. Suspendisse potenti. Ut tortor odio, venenatis non congue quis, mollis in sapien. Phasellus condimentum nulla elit, at scelerisque metus volutpat non. Proin dui justo, ornare eu luctus vel, pretium sit amet leo. Etiam eget odio sit amet velit blandit accumsan. Etiam finibus fermentum diam sit amet sodales. Curabitur fringilla vel purus vel dignissim. Integer venenatis quam id nisl auctor, eget dictum eros semper. Quisque quis arcu est. Nulla facilisi. Ut a mollis tellus. Sed vulputate at turpis posuere ultrices. Ut finibus ante eget lacinia malesuada.

Etiam nunc elit, ornare quis convallis at, mattis ac ligula. Donec vehicula tortor mollis, lobortis ante et, bibendum eros. Etiam felis turpis, ornare sed malesuada in, rhoncus eu est. Vivamus porta sem lacus, ac sollicitudin tortor volutpat ut. Nulla vel pharetra massa, ac cursus eros. Suspendisse finibus dignissim nulla quis facilisis. Donec mattis pretium elit pellentesque ullamcorper. Nam eu metus at odio pretium gravida a ac metus. Morbi in pretium dui, at mollis erat. Nullam imperdiet ex ut massa efficitur viverra.

Nullam mattis viverra dignissim. Donec sed ex porttitor, accumsan ante blandit, auctor ante. Nullam ultricies, nulla sit amet tincidunt mollis, massa enim scelerisque mauris, ac sodales dui ligula non metus. Phasellus vestibulum rutrum nisi in aliquet. Sed bibendum leo nulla, vehicula laoreet nulla molestie vel. Aenean auctor sodales leo. Nam in diam aliquam, rutrum mauris nec, tincidunt lorem. Vivamus at euismod purus, in feugiat ex. Sed nec interdum odio. Nullam euismod elit mauris, rhoncus porttitor lorem luctus vel. Aenean mollis eros eu tempor iaculis. Praesent et arcu auctor, blandit nisl id, bibendum diam. Nunc interdum felis enim, porta volutpat odio consequat ut.

Vivamus dapibus lobortis nisi, sit amet dapibus libero rutrum at. Morbi sed rhoncus magna. Ut quis convallis quam. In semper rutrum feugiat. Nunc in euismod lacus. Phasellus a arcu eget quam iaculis elementum vitae ultricies nisl. Mauris pharetra lobortis lectus, vitae egestas ex dictum bibendum.

Aenean lacinia erat sed ex imperdiet, ut auctor libero placerat. Curabitur gravida vulputate lacus, eu egestas enim volutpat eget. Vestibulum tincidunt enim at dolor nullam. 
""")
